### PR TITLE
Enable first batch of units.

### PR DESCRIPTION
**Pull request by ABrandau**
I coded all the units into to game by copy and pasting the leopard to check their consistency. After that rendered again the m577 and the lars using a different background. Also, I fixed the small shadow issues of the leopard (I believe).

Please check if the lars and the m577 look better than the rest, I'd rather re render all the units again with the different background than fix all the other units by hand.

### CODE REVIEW

**Comment by obrakmann** [comment]
Hmm... I have several observations:

* didn't notice any difference between the m577, lars and the rest
* the down-scaled marder looks *much* better than the rest. It is much less pixelated.
* The downside of the `Scale` option is that it causes the animations to go jerky. Both turret and unit being wobbling around when moving. I'm afraid that makes it unusable.
* The size of the units overall needs more work. At regular size, the units are very hard to make out, especially the fuchs and luchs. (that might be due to being heavily pixelated as well, can't tell without comparing). Also, some units have the wrong relative size compared to other units:
 * the m577 needs to be a little bit smaller.
 * the rocket pods on the lars need to be smaller as well, the truck itself a little bigger probably
 * the m109 needs to be a tiny bit smaller than the leopard2.

Heavily zoomed in screenshot, showing how the marder is less pixelated:
screenshot from 2015-12-04 21 20 43

Another shot just showing all units (w/o the scale option on the marder, and with double-pixeling):
screenshot from 2015-12-04 20 59 54

and without double-pixeling:
screenshot from 2015-12-04 21 00 35

**Comment by ABrandau** [comment]
The main difference is that the m577 and lars have no black pixels around them, or atleast less. shall I start re-rendering all the assets with the new background... to avoid having those black dots?

Confirm me that and I shall start working on getting the sizes right.

**Comment by ABrandau** [comment]
untitled

After some time testing different rendering methods, along with some help from Graion Dilach, I finally managed to get rid of the dark dots on the units, see the marder and fuchs, I also made the turret of the leopard smaller and cleaned it a little, tho I think it got worse.

The marder barrel is too small in comparison to everything else, on that scale it simply can't be seen, I hope the unit is smaller than what it should really be.

The luchs remains unmodified.

**Comment by obrakmann** [comment]
Yeah, I think it does look better without those dots. I still wonder though why everything looks so small. The original .shps are the same size and are much more recognizable. I think I'm gonna add an 2tnk or something from ra to the yaml and compare those. (but tomorrow, bed time now). (and yeah, the marder should probably be bit larger than that)

**Comment by ABrandau** [comment]
wargame
Did a second render row, I was expecting better results, I have a big size render stocked somewhere in case resizes are needed (and I'm expecting there will be).

**Comment by ABrandau** [comment]
Updated.
I had to add must be destroyed to the tanks to avoid some instant defeat problems.
image

**Comment by obrakmann** [comment]
Are those your original shps, or did you redo them with the models I linked?

**Comment by abcdefg30** [comment]
Btw, how does it come that every tank is the `Main Battle Tank of the German Army.`? :p

**Comment by obrakmann** [comment]
@abcdefg30: it's just placeholders.

I'm going to completely replace the current history and contents of this repo with a new one based around a support dir-based mod soon, anyway (so that it's not a clone of the openra repo anymore).

**Pull request closed without merging**
